spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cosmomi_dev_201811?allowMultiQueries=true&amp;useUnicode=true&amp;characterEncoding=utf8&amp;autoReconnect=true&amp;allowMultiQueries=true&amp;useSSL=true
    username: xuht
    password: xuht
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 10
      validatin-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      use-global-data-source-stat: true
      stat:
        enabled: true
        db-type: mysql
        log-slow-sql: true
        slow-sql-millis: 1000
        merge-sql: true
      slf4j:
        enabled: true  
      stat-view-servlet:
        enabled: true
        login-username: druid
        login-password: druid    
     
#security:
#  user:
#    name: leaf
#    password: leaf2018
ehcache:
  config: ehcache.xml    
                    
logging:
  config: classpath:log4j2.xml 

#file store mode   1:LOCAL- LOCAL FILE SYSTEM  2:FTP - FTP SERVER
#file store path pre   -- compat for LOCAL AND FTP
file:
  store:
    mode: LOCAL
    path-pre: D:/LOCALFILESTORE
    ftp-ip: 127.0.0.1
    ftp-port: 21
    ftp-username: ftpuser
    ftp-password: ftppass
  preview:
  #file preview store path
    store-path: D:/LOCALFILESTORE/preview

operation:
  database:
    backup_dir: /home/leaf/dbback/
    
